### ISSUE TITLE
Clarify readme with regards to redundant properties

### ISSUE THREAD

**Issue by kwin** [ciechanowiec/jcrcleaner#1]
Some of those protected properties are crucial (because they are not automatically set during package import). For a concrete use case look e.g. at https://github.com/Netcentric/aem-replication-metadata-validator.
In general only those protected properties which are marked as [autocreated](https://developer.adobe.com/experience-manager/reference-materials/spec/jcr/2.0/3_Repository_Model.html#3.7.2.3%20Auto-Created) can potentially be excluded from DocView serializations (as they should be maintained by the importing repository like `jcr:created`). Those are already listed in https://github.com/apache/jackrabbit-filevault/blob/1b17c1c51f0ba0b6a1ed416068cb5d6b185e418f/vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/DocViewSAXFormatter.java#L112 (e.g. `jcr:created` is never serialized in case the property is protected).

Excluding the `jcr:lastModified` property has an effect on the package import (although this property type is in most cases marked as `autocreated`, compare with https://developer.adobe.com/experience-manager/reference-materials/spec/jcr/2.0/3_Repository_Model.html#3.7.11.8%20mix:lastModified). The import works in a way that the `jcr:lastModified` date is set to what it has been in the exporting repository (i.e. restores its original value). That is very often desired, so I disagree with the evaluation that those are redundant.

**Comment by ciechanowiec** [comment]
@kwin, thank you for reporting the issue.

You are correct. Not all runtime-generated JCR properties can be treated as redundant. On the contrary, in some cases like the one you described, some of those properties are even desirable. To address this fact, I have updated the documentation accordingly, making it less categorical and avoiding the description of runtime-generated properties as "redundant." Should you have any other suggestions, feel free to reach out to me.
